Fix small issues
mexca/mexca pull request #27
Opened 2022-08-30 11:34 UTC by maltelueken

Fixes #26 #24

2022-09-08 14:00 UTC, dafnevk reviewed
I did not look in detail to the code, but tried out the installation / running instructions and read the documentation.

In general, looks very good! See the comments for some details.

2022-09-08 14:01 UTC, dafnevk commented on docs/docker.rst
> +  docker run -t -v absolute/path/to/video/folder:/test mexca:stable -f test/video_file -o test/output.json
This is only an issue with the stable version, the `devel` version works:
```
docker run -t -v /home/dafne/mexca/mexca/tests/test_files/:/test mluken/mexca:devel -f /test/test_video_audio_5_seconds.mp4 -o /test/output.json
```

2022-09-08 14:55 UTC, maltelueken commented on docs/docker.rst
> +  docker run -t -v absolute/path/to/video/folder:/test mexca:stable -f test/video_file -o test/output.json
Fixed! I changed the image to `mluken/mexca:latest` so that either the latest release or development version is pulled.

2022-09-09 12:11 UTC, maltelueken commented on docs/command_line.rst
> +  python bin/pipeline.py -f path/to/video_file -o output.json
I added the script to the package setup file and renamed it as you suggested. However, when installing mexca in a virtual environment it can be tricky to find the location of the script as it is not added to the normal system path (I added a note on that in the docs).

2022-09-12 12:49 UTC, dafnevk requested changes
Looks good, only the documentation on the command line tool needs to be updated.

2022-09-12 12:49 UTC, dafnevk commented on docs/command_line.rst
> +  python mexca-pipeline.py -f path/to/video_file -o output.json
This can be updated now:
```suggestion
  mexca-pipeline -f path/to/video_file -o output.json
```

2022-09-12 12:49 UTC, dafnevk commented on docs/command_line.rst
> +  python bin/mexca-pipeline.py -f path/to/video_file -o output.json
```suggestion
./bin/mexca-pipeline -f path/to/video_file -o output.json
```

2022-09-12 12:49 UTC, dafnevk commented on docs/command_line.rst
> +  python bin/mexca-pipeline.py -f path/to/video_file -o output.json
In principle, navigating to the directory should not be necessary when the environment has been activated.

2022-09-12 14:07 UTC, maltelueken commented on docs/command_line.rst
> +  python bin/mexca-pipeline.py -f path/to/video_file -o output.json
True, I left the note there in case it doesn't work for some users.

2022-09-12 14:48 UTC, merged